# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec89c2d95f9b81d6110d52584387d0c424a13f4bccd3a940c41df107037f4346d8b74d44f2df922a1e742185b932eb6a402c2df838a1f3a879e0c98072d3d330

test:
  secret_key_base: e1e46b59942a91ff5a3956fba24f317406a0532ebffb1ec8db8047ede5ca130168eb39a6e1594b4a8db625fb9274db9f1486f96a4f138153539d5200d0f61c7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
